config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  devise_for :users
  resources :groups  do 
  resources :exchanges
  end
  resources :users

  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
  
    unauthenticated do
      root "splash#index", as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :groups
  validates :name, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/exchange_group.rb
class ExchangeGroup < ApplicationRecord
  belongs_to :exchange
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :exchanges
  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    exchanges.sum(:amount)
  end

  def recent_exchanges
    exchanges.order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :exchanges
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_exchange, only: %i[show edit update destroy]

  # GET /exchanges or /exchanges.json
  def index
    @exchanges = Exchange.all
  end

  # GET /exchanges/1 or /exchanges/1.json
  def show; end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new
    @group = Group.find(params[:group_id])
    @categories = Group.where(user_id: current_user.id)
  end

  # GET /exchanges/1/edit
  def edit; end

  # POST /exchanges or /exchanges.json
  def create
    params = exchange_params
    @exchange = Exchange.new(name: params[:name], amount: params[:amount])
    @exchange.author = current_user
    @categories_ids = params[:group_ids]
    @categories_ids.each do |id|
      group = Group.find(id) unless id == ''
      @exchange.groups.push(group) unless group.nil?
    end

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to groups_url, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @exchange }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exchanges/1 or /exchanges/1.json
  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html { redirect_to exchange_url(@exchange), notice: 'Exchange was successfully updated.' }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1 or /exchanges/1.json
  def destroy
    @exchange.destroy

    respond_to do |format|
      format.html { redirect_to exchanges_url, notice: 'Exchange was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exchange
    @exchange = Exchange.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def exchange_params
    params.require(:exchange).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.new(group_params)
    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exchanges/_form.html.erb
<%= form_with(model: exchange, url:  group_exchanges_url(group) )do |form| %>
  <% if exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
        <% exchange.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , required: true %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount  , required: true%>
  </div>


  <div class="field">
    <%= form.label :groups %>
    <%= form.select :group_ids, @categories.collect {|category| [category.name, category.id]}, { include_blank: false }, required: true, multiple: true %>
    </div>
</main>

  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editing Exchange</h1>

<%= render 'form', exchange: @exchange %>

<%= link_to 'Show', @exchange %> |
<%= link_to 'Back', exchanges_path %>

app/views/exchanges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exchanges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>User</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exchanges.each do |exchange| %>
      <tr>
        <td><%= exchange.name %></td>
        <td><%= exchange.amount %></td>
        <td><%= exchange.author_id %></td>
        <td><%= link_to 'Show', exchange %></td>
        <td><%= link_to 'Edit', edit_exchange_path(exchange) %></td>
        <td><%= link_to 'Destroy', exchange, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exchange', new_exchange_path %>

app/views/exchanges/new.html.erb
<div class="login-session" > 
<%= form_with(model: @exchange, url:  group_exchanges_url(@group) )do |form| %>

    <header>
      <nav >   
        <a onclick="history.back()"><i class="fas fa-arrow-left text-2xl"></i></a>
        <h1>New Exchange</h1>
        <div class="actions">
          <%= form.submit "Create" %>
        </div>
      </nav>
    </header>

<% if @exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
        <% @exchange.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.text_field :name, required: true, placeholder:"Exchange Name"%>
  </div>

  <div class="field">
    <%= form.number_field :amount, required: true, placeholder:"Amount"%>
  </div>


  <div class="field">
    <%= form.select :group_ids, @categories.collect {|category| [category.name, category.id]}, { include_blank: false }, required: true, multiple: true, Class: "select" %>
        
    </div>

<% end %>


</div>

app/views/exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exchange.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @exchange.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @exchange.user_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @exchange.Group_id %>
</p>

<%= link_to 'Edit', edit_exchange_path(@exchange) %> |
<%= link_to 'Back', exchanges_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name%>
    <%= form.text_field :name, required: true%>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon, required: true%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
  <% if user_signed_in? %>
  <div class="nav-container">

<ul class="nav-bar">

  <li class="nav-item">
    <h2>
      <%= "#{current_user.name}" %>
    </h2>
  </li>
    <li class="nav-item">
     <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
</ul>
</div>
 <% end %>

<p id="notice"><%= notice %></p>

 <div class='group-container'>

<ul>
  <% @groups.each do |group| %>
    <li>
    <div>
    <img src="<%= group.icon %>">
    <div>
        <%= link_to group.name, group_path(group)%>
      <p><%= group.created_at.strftime("%d %b %Y") %></p>
    </div>
    </div>
          <p>$<%= group.total_amount%></p>
    </li>
  <% end %>
</ul>


<div class="add-div">
<%= link_to 'New Category', new_group_path %>
</div>
</div>

app/views/groups/new.html.erb
<div class="login-session" > 
<%= form_with(model: @group) do |form| %>

    <header>
      <nav >   
        <a href='/'><i class="fas fa-arrow-left"></i></a>
        <h1>New Category</h1>
        <div class="actions">
          <%= form.submit "Create" %>
        </div>
      </nav>
    </header>

<% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% @group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, required: true, placeholder:"Category Name"%>
  </div>

  <div class="field">
    <%= form.text_field :icon, required: true, placeholder:"IconURL"%>
  </div>

<% end %>


</div>

app/views/groups/show.html.erb
  <% if user_signed_in? %>
  <div class="nav-container">

<ul class="nav-bar">

  <li class="nav-item">
  <a href='/'><i class="fas fa-arrow-left"></i></a>
  </li>
   <h2>
      <%= @group.name %>
    </h2>
</ul>
</div>
 <% end %>

<p id="notice"><%= notice %></p>

<div class='group-info-div'>

<p>Total Amount:</p>
<p>$<%=@group.total_amount%></p>

</div>

<div class='group-container'>

<ul>
  <% @group.recent_exchanges.each do |exchange| %>
    <li>
    <div>
    <div>
        <%=exchange.name%>
      <p><%= exchange.created_at.strftime("%d %b %Y") %></p>
    </div>
    </div>
          <p>$<%= exchange.amount%></p>
    </li>
  <% end %>
</ul>

<div class="add-div">
<%=link_to 'New Exchange', new_group_exchange_path(@group) %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="splash-title">
<h1>Budget App</h1>
</div>
<div class="splash-sign">
<ul>
<li>
  <%= link_to "LOG IN", new_user_session_path, class: "nav-link" %>
 </li>
<li>
    <%= link_to "SIGN UP", new_user_registration_path, class: "nav-link" %>
</li>
</ul>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>